[package]
name = "sculd"
version = "0.2.0"
authors = ["ishiy <y.ishihara.1993@gmail.com>", "Yusuke Miyazaki <miyazaki.dev@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
chrono = "~0.3"
getopts = "~0.2"
reqwest = "~0.9"
serde_json = "~1.0"
